local buffer = require("daylog.buffer")
local daybook_io = require("daylog.daybook_io")

local M = {}

-- Install the daybook post-commit audit hook (shell).
--
-- Writes a `post-commit` hook into the daybook's git repo that runs scripts/commit-audit.lua on each
-- commit. The plugin path is baked in (the script self-locates the rest), so the generated hook has
-- nothing to edit. Refuses to clobber an existing hook unless `opts.force`.

local warn = buffer.warn

-- git in `dir`; returns its trimmed first stdout line and whether it succeeded.
local function git(dir, args)
  local command = { "git", "-C", dir }
  vim.list_extend(command, args)
  local out = vim.fn.systemlist(command)
  return (out[1] or ""), vim.v.shell_error == 0
end

-- The absolute path of the shipped scripts/commit-audit.lua, or nil when it is not on the runtimepath.
local function script_path()
  local found = vim.api.nvim_get_runtime_file("scripts/commit-audit.lua", false)
  return found[1] and vim.fn.fnamemodify(found[1], ":p") or nil
end

-- The daybook repo's hooks directory (honoring core.hooksPath), created if missing. Returns dir, or
-- nil and an error message when `root` is not inside a git repo.
local function hooks_dir(root)
  local gitdir, ok = git(root, { "rev-parse", "--absolute-git-dir" })
  if not ok then
    return nil,
      "daylog: "
        .. root
        .. " is not a git repository; run git init there first (see docs/version-control.md)"
  end

  local hooks
  local configured = git(root, { "config", "--get", "core.hooksPath" })
  if configured ~= "" then
    hooks = configured:sub(1, 1) == "/" and configured
      or (git(root, { "rev-parse", "--show-toplevel" }) .. "/" .. configured)
  else
    hooks = gitdir .. "/hooks"
  end

  vim.fn.mkdir(hooks, "p")
  return hooks
end

local function hook_lines(script)
  return {
    "#!/usr/bin/env bash",
    "# daylog commit-audit hook (generated by require('daylog').install_commit_audit_hook()).",
    "# Classifies each commit's .day changes: notes / today / other-day. See docs/version-control.md.",
    "set -euo pipefail",
    "",
    "SCRIPT=" .. vim.fn.shellescape(script),
    "",
    "# Fast path: a commit touching no .day file is trivially notes-only -- skip starting nvim.",
    "# --root so the very first (parentless) commit's added files are still seen.",
    "if git diff-tree --root --no-commit-id --name-only -r HEAD -- '*.day' | grep -q .; then",
    '  nvim --clean -l "$SCRIPT" commit HEAD || true',
    "else",
    "  git notes --ref=daylog add -f -m notes HEAD || true",
    "fi",
  }
end

-- Install the hook into `opts.dir` (default: the configured daybook.root). `opts.force` replaces an
-- existing hook. Returns the hook path on success, or nil after warning.
function M.run(opts)
  opts = opts or {}

  local script = script_path()
  if not script then
    warn("daylog: could not locate scripts/commit-audit.lua on the runtimepath")
    return nil
  end

  local root = opts.dir and vim.fn.fnamemodify(vim.fn.expand(opts.dir), ":p")
  if not root then
    local settings = daybook_io.expanded_daybook_settings()
    if not settings then
      warn("daylog: daybook.root is not configured; pass { dir = <daybook git repo> }")
      return nil
    end
    root = settings.root
  end

  local hooks, err = hooks_dir(root)
  if not hooks then
    warn(err)
    return nil
  end

  local hook = (hooks:gsub("/$", "")) .. "/post-commit"
  if vim.fn.filereadable(hook) == 1 and not opts.force then
    warn(
      "daylog: a post-commit hook already exists at "
        .. hook
        .. "; pass { force = true } to replace it"
    )
    return nil
  end

  if not pcall(vim.fn.writefile, hook_lines(script), hook) then
    warn("daylog: could not write the hook to " .. hook)
    return nil
  end
  vim.fn.setfperm(hook, "rwxr-xr-x")

  vim.notify("daylog: installed commit-audit hook at " .. hook, vim.log.levels.INFO)
  return hook
end

return M
