-- Pure tests for the OkLCH colour-wheel generator: each activity index maps to a distinct,
-- in-gamut colour with a 256-colour fallback, generated by golden-angle hue stepping.
return function(t)
  local palette = require("daylog.palette")

  t.test("palette.color generates the expected colours", function()
    -- Frozen goldens (greedy farthest-point in OkLCH/OkLab); deterministic on the LuaJIT matrix.
    t.eq(palette.color(1).gui, "#619ce7")
    t.eq(palette.color(2).gui, "#fce765")
    t.eq(palette.color(3).gui, "#96290a")
    t.eq(palette.color(4).gui, "#6e9109")
    t.eq(palette.color(1).cterm, 74)
  end)

  t.test("activity colours have distinct 256-colour codes (no cterm collisions)", function()
    -- The farthest-point search keeps colours apart in OkLab; that also keeps their xterm-256 codes
    -- distinct, so terminals without `termguicolors` never render two activities identically.
    local seen = {}
    for i = 1, 24 do
      local ct = palette.color(i).cterm
      t.ok(not seen[ct], "cterm " .. ct .. " (index " .. i .. ") is not already used")
      seen[ct] = true
    end
  end)

  t.test("palette.color yields valid hex and an xterm-256 code at any index", function()
    for i = 1, 40 do
      local c = palette.color(i)
      t.ok(c.gui:match("^#%x%x%x%x%x%x$") ~= nil, "valid hex at index " .. i)
      t.ok(c.cterm >= 16 and c.cterm <= 255, "cterm in [16,255] at index " .. i)
    end
  end)

  t.test("consecutive activity colours differ", function()
    for i = 1, 24 do
      t.ok(palette.color(i).gui ~= palette.color(i + 1).gui, "index " .. i .. " differs from next")
    end
  end)
end
